### ISSUE TITLE
LC Multiple Choice template

### ISSUE THREAD

**Issue by MarOrt** [danb-dliflc/GLOSSActivities#21]
•	No cross to close Instructions, More info or TN, also all peripheral pages
•	When one answer is click and Submitted, the other choices are dead and do not respond before you click “reset” – the present MC template shows feedback as soon as a choice is clicked, which promotes further interest to click other choices.
•	 Hint – would be much better if it had a frame to see that it is clickable. / It does have a cross to close it
•	 Submit button – is too low on the page – can it be closer to the choices, better still not to have it at all and get feedback right after a choice is clicked
•	 Pop-up windows cannot be moved around the screen – it was a very convenient feature – we could see the feedback alongside with the questions, or a transcript alongside with the questions
•	 Glossary the cursor does not change into a hand when hovering over the audio icon
•	Glossary – the Close button does not work
•	Test – one page, one click!
Are_cul433 – general comments
Are_ecn428 – general comments
Cm_cul429 - general comments
Cm_mil405 - general comments

Cm_pol412 – Alternate audio does not load in any browser – in the original on our regular site it does not show an alternate audio at all
 Hb_ecn402 - general comments / there are two lessons with the same number hb_ecn402 – two links take to two different lessons
Hb_env403 -- general comments
Hb_geo403 --- general comments
 Fr_tec401 - general comments – there is only one lesson with this template 
ps_cul428 – general comments
ps_cul430 - unable to load alternate audio / there is no alternate audio in the original
ps_ecn407 - general comments
 ru_cul252 - general comments
ru_cul262- general comments
ru_cul293 - general comments
ru_cul296 – the link to an html page from the TN is not working – it works on our regular site
q2 html link is not working

**Comment by ti-dm** [comment]
Resolved & updated.
