### ISSUE TITLE
R-Scanning

### ISSUE THREAD

**Issue by dohee-koo** [danb-dliflc/GLOSSActivities#22]
**Fonts:**

1. Size 2 fonts look really small.

2. Three fonts are used here: Times Roman (Lesson Info & Source), Arial (Resources, Glossary, activity text [passages and answer options]), and FuturaMedium (Buttons, feedback, instruction, teacher note, additional note, etc.). My suggestion is that except the buttons, all fonts should be Arial. FuturaMedium is cute and great for buttons, but it may not be the best font for extended text, especially in italic.
Personally, I like Arial for extended text as it’s comfortable to read (even in italic) and may be I’m too used to it in GLOSS lessons. Users must be used to that font too.

**Audio player:**

3. In the audio play bar, when you click the curvy arrow (playback button?), instead of the audio being played back, two small triangles appear: green and red. If I click one more time, they disappear. What are they for? The green & red triangles, the play back arrow, all are not intuitive. 

4. Some lessons do not have audio files for the glossary items. In that case, when I moved the progress bar or played with the green and red triangles, the letters NaN:NaN appeared and pushed the buttons to the right. So, the volume button appeared right above the word "Glossary." Please see the attachment. 

**Feedback:**

5. In an old LO, the built-in feedback and the developer-provided feedback are divided by the lines. In the new interface, there is no division for some (not all) intermediate feedback. If students can distinguish these two different sources of feedback, it will be better. Just adding a simple line or line break will work between the built-in feedback and the developer feedback. For some feedback, I see a line break. So it is inconsistent.

**Miscellaneous:**

6. Let students print the source. Give the button “Print” like in Glossary.
7. In ps_cul332, the text in the Teacher's Note and feedback (both intermediate and final) is aligned to the right. See the attachment. The original LO doesn't have that issue.

![nannan](https://cloud.githubusercontent.com/assets/16672583/12992564/0c3cab7a-d0ca-11e5-87f7-725f81a986c8.jpg)
![nannan_2](https://cloud.githubusercontent.com/assets/16672583/12992572/11d89ec2-d0ca-11e5-927d-f27167a74667.jpg)
![text_alignment](https://cloud.githubusercontent.com/assets/16672583/12992578/1bb10524-d0ca-11e5-9f80-8139a2d8a528.jpg)

**Comment by ti-dm** [comment]
Resolved & updated.
