### ISSUE TITLE
RC_Multiple choice

### ISSUE THREAD

**Issue by XiaomeiSchnittgrund** [danb-dliflc/GLOSSActivities#23]
Lessons tested: cm_geo061, cm_ mil007,fr_sci301,fr_sci306, hbw_ecn308, hbw_mil302, ps_soc319, ps_soc346, ru_cul027, ru_tec010...
1) Reset button is hard to see.  Suggest: to make the letters **Reset** darker
 Is it possible to skip the Reset (button) action? Make like the current GLOSS one, just click (any choices) and pop up the answer. 
2) Question Space may be too small. Is it possible to make the space larger? 
3) All scroll bars are too narrow. Is it possible to make the scroll bar itself wider?  
4) Is it possible to eliminate the font color in FBs? Some old lessons have multiple colors of fonts (cm_mil007) in their FBs. It seems that when those lessons transfer to this “new one”, the original font colors remain. 
5) Source page is very narrow, especially when one clicks on the translation page. The font is too small to read. The character button 簡 should be 简 (simplified). 
6) In IE 11: All scroll bars are not working.
6) In Firefox: the title looks like it has different font sizes, some characters are bolded; numbers in the title seem to be a larger size (hbw_mil302)
7) In iPad: the text on the left is hard to move up and down (the scroll bar is too narrow to hold on to) 
8) In Chrome: when I open each lesson in Chrome, a pop up automatically appears, which is not in other browsers. After clicking on “Nope”, it disappears.

**Comment by ti-dm** [comment]
Resolved & updated.
