### ISSUE TITLE
Glossary - audio icons not showing up

### ISSUE THREAD

**Issue by wendy-dliflc** [danb-dliflc/GLOSSActivities#24]
Audio icons next to words not showing up in some lessons. 

http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/kur_sci425.xml&glossLoadActivityIndex=4&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/

![image](https://cloud.githubusercontent.com/assets/11760923/13094213/305dba24-d4be-11e5-9a15-080078ff56e0.png)

**Comment by dohee-koo** [comment]
Wendy,
not all GLOSS lessons have audio files in Glossary.

**Comment by wendy-dliflc** [comment]
Ok, thanks!
