### ISSUE TITLE
Glossary - various fixes

### ISSUE THREAD

**Issue by wendy-dliflc** [danb-dliflc/GLOSSActivities#26]
1.) Don't need arrows for custom scrollbar. 
2.) Don't need "Print" and Close" buttons. (Note from meeting on 2/17 - Julia will look into whether or not "Print" is needed)
3.) Font-family should be: 
                 font-family: Helvetica Neue,Helvetica,Arial,sans-serif;

**Comment by wendy-dliflc** [comment]
Also,
4.) Audio icons should be the latest icons.

**Comment by wendy-dliflc** [comment]
Additions from meeting and testing from others: 
5.) The cursor should change into a hand when hovering over the audio icon.
6.) Get rid of word "Glossary" title at the top.
7.) Sometimes there is no audio for glossary. In these cases, do not display audio player. Also, in cases when audio player is empty and you click play, NaNNaN appears and buttons get moved over.  
8.) Speaker image should appear next to target language.

**Comment by lingnet** [comment]
2) updated, 
3) font-family updated, 
4) updated image.

**Comment by lingnet** [comment]
6) updated

**Comment by lingnet** [comment]
7) updated, In case threre is no audio, the player will not display. 

http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/ad_cul209.xml&glossLoadActivityIndex=1&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/

**Comment by lingnet** [comment]
8) updated

**Comment by wendy-dliflc** [comment]
From issue #38, renumbered to match numbering for this issue: 

9.) Glossary
A. There is too much space on the right, especially when there are no audios and audio icons. Consider moving the text to the right a little bit.
B. The texts of right-to-left languages are aligned to the left. They should be aligned to the right. (hbw_mil303, hbw_pol307, ps_cul328, ps_ecn325)

10.) Location of audio icons
Audio icons are on the right. They should be on the right for right-to-left languages only, but for now, they seem to be on the right for all languages. Please see the attachment of ru_cul224. [Note - refer to issue #38 for attachments]

**Comment by wendy-dliflc** [comment]
11.) We are waiting to hear back about whether or not we want the Print button, but if we do have the Print button, I noticed in the following lesson that if you scroll down a little in the Glossary, and then click "Print", the "Print" page that pops up does not contain everything. 

http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/fr_env305.xml&glossLoadActivityIndex=3&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/

**Comment by MarOrt** [comment]
It looks really very strange and not like the glossary itself ! There was feedback from some users that it was a desirable feature. Is it possible to make it work right?

**Comment by lingnet** [comment]
10) audio icons updated, text spacing and align can changed to right.

**Comment by lingnet** [comment]
9.) Glossary

A. text spacing updated to more right (text space right)

B. the text is aligned to the right. (text align right)
(hbw_mil303, hbw_pol307, ps_cul328, ps_ecn325)

**Comment by lingnet** [comment]
10.) Location of audio icons - (changed to left)

**Comment by lingnet** [comment]
11.) print screen popup height, weight size doubled but, print functions is out dated code.
- need to update print button, code more user friendly. 3/11/2016

**Comment by lingnet** [comment]
5) arrow showing as hands - css tested

**Comment by wendy-dliflc** [comment]
9.) B. rtl languages do not seem to be showing up right-aligned for the target language:
Example: 
http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/ps_cul328.xml&glossLoadActivityIndex=2&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/

**Comment by lingnet** [comment]
9.) B. rtl languages do not seem to be showing up right-aligned for the target language:

GosLeft ( LTR, RTL) is updated..

**Comment by lingnet** [comment]
![image](https://cloud.githubusercontent.com/assets/1678868/13899148/52af710a-eda3-11e5-93ca-bf58872652de.png)

**Comment by wendy-dliflc** [comment]
From Issue #42 testing from Xiaomei: 

1.) TL should be in the first column, not English.

Wendy's comments for this issue: 
			Aaron - I know you mentioned this has to do with the way that it's entered into the generator, but are the two fields switched around? Here are two examples where you can see in the last version the columns are in the opposite order of the new version.
			Hebrew:
				a.) http://gloss2.lingnet.org/products/gloss/hbw_pol302/hbw_pol302_act1.html
				b.) http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/hbw_pol302.xml&glossLoadActivityIndex=1&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/
			Chinese:
				a.) http://gloss2.lingnet.org/products/gloss/cm_geo306/cm_geo306_act1.html
				b.) http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/cm_geo306.xml&glossLoadActivityIndex=1&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/

2.) The layout of vocabulary print out list still remains one column instead of two.

----------------
From Wendy: 
Julia looked into it and we will have the Print button for Glossary & Source. The button will likely be an image of a printer - we sent an e-mail to Mike about this. 

Since we will have the Print button, I just wanted to mention the issue from March 8: 

3.) I noticed in the following lesson that if you scroll down a little in the Glossary, and then click "Print", the "Print" page that pops up does not contain everything.

http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/fr_env305.xml&glossLoadActivityIndex=3&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/

**Comment by wendy-dliflc** [comment]
Update: Got the print icon from Mike (thanks!). It is called "icon_print_gray.png" and is in gloss2.lingnet.org/headstarthtml/templates/common/img

**Comment by lingnet** [comment]
updated print icon but print function old legacy code need to modernize or replaced to better one.
aligned little bit right side, need adjustment in styles.

http://gloss2.lingnet.org/headstarthtml/templates/common/img/icon_print_gray.png

**Comment by lingnet** [comment]
1.) TL and English word is seperate GlosLeft, GlosRight in xml file, code div showing randomly different. Can be changed <div> issues.
2) Content area printing preview layout issue is changed, will change and remove comfirm prompt.
3) window.print() function ignores second pages when printing. will change printing code.

**Comment by lingnet** [comment]
1) Hebrew and Chinese XML file different direction attribute in XML file.
in order to fix XML file GlosLeft, GlosRight should be consistent. Hebrew has GlosLeft with English texts and GlosRight for target language.  ( can be manually switched for Hebrew only).
http://gloss2.lingnet.org/products/gloss/hbw_pol302/hbw_pol302.xml
http://gloss2.lingnet.org/products/gloss/cm_geo306/cm_geo306.xml

2) updated.
3) updated, know printing 2 pages without problem.

**Comment by wendy-dliflc** [comment]
Looks good, thanks!

**Comment by wendy-dliflc** [comment]
1.) Both clicking on the audio icon and clicking on the target language should result in the audio being played for that item.
2.) Audio icon should appear next to the target language (like in the current version).

**Comment by wendy-dliflc** [comment]
Moved from issue #44 (Fill in the Blank testing by Dohee):

3.) Italic font looks big in Glossary (check fr_soc310).

4.) fr_sec301: In Glossary, the audio icons are on the right, so the layout is: 
French –-- English –-- audio icon

**Comment by lingnet** [comment]
2) updated, - audio icons appears after left, right and audios, target language is defined in XML as either GlosLeft, GlosRight, - can't figure out how the language in specified from code.

will compare with old GLOSS Lo's 

3) updated, - removed overlapping styles
4) XML file formats - <A_Type> [GG] - GlosLeft has target languages, GlosRight has English.
(It's already working in order as left, right inputs)

<GlosLeft dir="ltr" esbox="0"><![CDATA[ désigner ]]></GlosLeft>
<GlosRight dir="ltr" esbox="0"><![CDATA[ refer to ]]></GlosRight>

**Comment by lingnet** [comment]
1) is updated, in XML file has GlosLeft, GlosRight and target language for Arabic is on Right, usually other language XML file has English on Right, However, I changed to play audio by clicking GlosRight text field. in order to identify target language require more information, Currently A Type:['GG'] has only three fields, GlosLeft, GlosRight, AUD_STIMULUS (audio filename). in general target language field were not consistent.

**Comment by wendy-dliflc** [comment]
1.) Doesn't seem to be looking at which one is the target language. Clicking on the target language should result in the audio being played for that item. Hovering over the item should also change the cursor to the hand icon and clicking on it should change the words to the blue-ish color that is used in audio hints. 

2.) Should be that the audio icon appears next to whichever is the target language. So, if the target language is on the left, then the audio icon should appear on the left. if the target language is on the right, then the audio icon should appear on the right.

For example, the audio icon should be on the left for this lesson:
http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/fr_soc310.xml&glossLoadActivityIndex=4&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/

The audio icon should be on the right for this lesson: 
http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/ad_cul039.xml&glossLoadActivityIndex=2&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/
