### ISSUE TITLE
Framework fonts & UI inconsistencies

### ISSUE THREAD

**Issue by mccumb01** [danb-dliflc/GLOSSActivities#28]
Based on viewing Reading_MC in the testing site: 
[Arabic ad_cul007](http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/ad_cul007.xml&glossLoadActivityIndex=4&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/)

Overall it's really looking great! Only noticed some minor things: 

![screen shot 2016-02-17 at 2 48 19 pm](https://cloud.githubusercontent.com/assets/1052245/13130204/68f8621c-d586-11e5-80dc-464bc31e3c0b.png)

1. The DLIFLC "Hamburger menu" in the upper-right (unless Branka/Julia know otherwise?) should not be included. That was from a much earlier design.  

2. GLOSS title should be "Georgia" font, #888; 28px bold, letter-spacing: 2px (not -2). Not sure it's centered in the screen, but that could just be me. Its position & styling is spread across 2-3 CSS files.

3. DLI logo is not in the header where it belongs semantically. Makes centering "GLOSS" a pain too. 

4. Lesson title should be 24pt; #444444; 
    - This particular lesson is rendering `<strong>` tags as text around the title (see screenshot)
    - Shouldn't have such tags in the title to begin with. If that's from the XML, should strip it out of all lessons. 
    - Title should rather use an h1 or h2 for semantic meaning, and CSS style for size/weight. 

4. `font-family:` needs to be changed in several places. gloss_Source.css, dlilearn_activities.css, and activityDefault.css are all using Futura Medium. GLOSS should not contain any Futura text.
    - Please change to: `font-family: Helvetica-Neue, Helvetica, Arial, Sans-serif` 
    - Please also replace `@font-face` links to include Helvetica-Neue & remove all references to Futura.     
    - If Helvetica-Neue is not properly included & is listed as the sole font, (as in the peripheral pages), then body text defaults to Times New Roman or whatever the browser default is. Need to have the whole list as a backup.

**Comment by wendy-dliflc** [comment]
1.) Taken out. 
2.) Changed.
3.) Centered GLOSS. Adjusted spacing to look and fit better after centering. 
4.) HTML tags taken out of title. Changed size and color of title. 
5.) Changed font-family for GLOSS to be: 
font-family: Helvetica-Neue, Helvetica, Arial, Sans-serif
Also have question and clarification needed about font (sent through e-mail)
