### ISSUE TITLE
Feedback pop-up

### ISSUE THREAD

**Issue by mccumb01** [danb-dliflc/GLOSSActivities#29]
Based on viewing Reading_MC in the testing site:
[Arabic ad_cul007](http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/ad_cul007.xml&glossLoadActivityIndex=4&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/)

A few notes on the  feedback pop-up: 

1. Title bar uses incorrect background color. Should be #207bbb;
2. Font-family is Futura Medium. Should be `font-family: "Helvetica-Neue", Helvetica, Arial, sans-serif` (should be addressed w/fixes in "General UI Inconsistencies" issue submitted earlier). 
3. "Close" button should be 36px circle and needs to adjust the "X" content.
     - In Firebug, for some reason setting both height & width to 36px made it oblong instead of a circle. That was weird ... As shown below, it was: 

```
{height: 30px; width: 36px; border-radius: 20px; /*or higher*/}
```
Either use the PNG graphic, or instead of an "X" in the div, use a "+" sized and transformed 45-deg.  
```
body[gloss="true"] #feedbackBtn {
    color: #aaa;
    font-size: 36px;
    font-weight: 100;
    line-height: 29px;
    transform: rotate(45deg);
}
```
   

4. Text content within the feedback box bumps up against the title & is really cramped. Needs 24pt top/bottom margins & adjusted line-height.
```
 #feedbackTextContainer {margin: 24px auto; line-height: 22px;}
```

What it is now: 
![screen shot 2016-02-17 at 3 54 56 pm](https://cloud.githubusercontent.com/assets/1052245/13131328/d98f9556-d58e-11e5-85d6-a5e6e0ea7fb2.png)

What the future may hold:
![screen shot 2016-02-17 at 3 52 30 pm](https://cloud.githubusercontent.com/assets/1052245/13131304/a997d372-d58e-11e5-950f-feb2fb39a1da.png)

**Comment by wendy-dliflc** [comment]
1.) Done. 
2.) Done. 
3.) Changed to still use the "X" and used the first set of specs given for an "X" in addition to "line-height: 29px".
4.) Modified, but used the following:
- A lot of feedback contains <p>, which leaves some space at top. Adjusting the margins to 24px would leave a big blank area on top in those cases. Adjusted #feedbackText to 12px so there is some space for feedback with no space already and doesn't make the space too big for items that already have some space on top.
- Also, line-height adjusted for #feedbackTextContainer to 22px.
