### ISSUE TITLE
Source Peripheral - Translation (ps_ecn411)

### ISSUE THREAD

**Issue by wendy-dliflc** [danb-dliflc/GLOSSActivities#36]
Moved from issue #35 (from Dohee's testing of Listening True-False):

ps_ecn411 --> In the source, the translation is on the right (it should be on the left). In feedback, Pashto is aligned to the left. It should be aligned to the right. The original LO doesn't have this problem.

Example:
http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/ps_ecn411.xml&glossLoadActivityIndex=2&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/

http://gloss2.lingnet.org/products/gloss/ps_ecn411/ps_ecn411_act2.html

**Comment by ti-dm** [comment]
Resolved & updated.
