### ISSUE TITLE
Audio Player - behavior during repeat/loop

### ISSUE THREAD

**Issue by wendy-dliflc** [danb-dliflc/GLOSSActivities#37]
Moved from issue #35 (from Dohee's testing of Listening True-False). This is general behavior with the audio player, not just in Listening True False:

The audio player --> 1) When I move the red triangle to the left and click play, the audio plays unlimitedly; 2) when I move both the green triangle and red triangle and click play, the audio plays unlimitedly; 3) when I move only the green arrow and click play, the player behaves differently. It's hard to describe. Please test. I am pointing this out because I can't exactly figure out how this player works, which means, it's not very intuitive.

**Comment by ti-dm** [comment]
Resolved as of 2/25
