### ISSUE TITLE
RC - True/false

### ISSUE THREAD

**Issue by dohee-koo** [danb-dliflc/GLOSSActivities#38]
**1. Font**
It may apply to other templates, but I found that the fonts in Glossary are smaller, and the fonts in Resources are bigger than normal (when the font size of the main text is considered normal). 

**2. Glossary**
A. There is too much space on the right, especially when there are no audios and audio icons. Consider moving the text to the right a little bit.
B. The texts of right-to-left languages are aligned to the left. They should be aligned to the right. (hbw_mil303, hbw_pol307, ps_cul328, ps_ecn325)

**3. Images in Source**
In some Chinese LOs, there is a broken (crossed out) image or icon ("View X," I guess). I also saw a broken image in ps_cul328. 

**4. NaNNaN still appears**
I believe you are working on this.

**5. Texts not centered on the buttons (IE)**
The texts on the buttons (instruction, more info, Teacher's Note): the texts should be centered. Now, they are aligned to the left. The texts are centered in Chrome and Firefox.

**6. Scroll bar**
It's not responsive in IE 11. I guess you are working on this.

**7. Source**
The right column looks bigger. Is it going to be expandable soon?

**8. Location of audio icons**
Audio icons are on the right. They should be on the right for right-to-left languages only, but for now, they seem to be on the right for all languages. Please see the attachment of ru_cul224. 

**9. The italics in Glossary**
The italic fonts look big (see attachment, it's either fr_env305 or fr_pol302, I couldn't write down clearly, sorry!)

**10. Feedback**
In the feedback of some right-to-left languages, the foreign language texts are aligned wrong way. They should be aligned to the right, but are aligned to the left (hbw_pol307, ps_cul328). 

![audio_icon](https://cloud.githubusercontent.com/assets/16672583/13610521/e939527e-e512-11e5-84fa-051153189ae2.jpg)

![glossary](https://cloud.githubusercontent.com/assets/16672583/13610522/eb9ab6ca-e512-11e5-8e49-bb7d420e8b30.jpg)

![glossary_font](https://cloud.githubusercontent.com/assets/16672583/13610524/ef471d2c-e512-11e5-9db6-e2f634a810d8.jpg)

**Comment by wendy-dliflc** [comment]
1.) a. For Glossary, the General Specifications say that the font-size should be 12px ("normal" size is 14px) - do we want to change this? 
b. Resources font-size has been changed to 14px for links and description. URLs are set to 12px as per the General Specs. 

2.) Moving this to separate issue - Glossary

3.) Moving this to separate issue - Source

4.) Did it appear in a peripheral (Glossary, Source, etc.) or in the Reading True False template itself? 

5.) Can look into this later - I think this should be a lower priority item. 

8.) Moving this to separate issue - Glossary. 

9.) This is because the developer put in <em> </em> tags (fr_env305). 

10.) Will look into this.

**Comment by wendy-dliflc** [comment]
10.) Issue fixed. Examples: 

http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/hbw_pol307.xml&glossLoadActivityIndex=3&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/

http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/ps_cul328.xml&glossLoadActivityIndex=2&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/
