### ISSUE TITLE
Source - Images (ps_cul328)

### ISSUE THREAD

**Issue by wendy-dliflc** [danb-dliflc/GLOSSActivities#39]
Moved from Issue #38 (testing for RC True False)

3. Images in Source
In some Chinese LOs, there is a broken (crossed out) image or icon ("View X," I guess). I also saw a broken image in ps_cul328.

http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/ps_cul328.xml&glossLoadActivityIndex=2&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/

**Comment by ti-dm** [comment]
Resolved & updated.
