### ISSUE TITLE
Get the point RC,LC &VID

### ISSUE THREAD

**Issue by XiaomeiSchnittgrund** [danb-dliflc/GLOSSActivities#40]
A very good feature to change the writing/display space and I hope the space (text) in “Source” can be made as large/flexible too. 
All scroll bars are still hard to move in IE 11, but there is no problem in IE 10, Firefox and Chrome.

**GLOSSAY**: **TL** should be in the first column, and then English. 
The font in Glossary is too light in color and small; suggest it be darker; I printed out the vocabulary list, the target language words are **not** side by side with English. Please check the layout of the pint-sheet.

 **Correct Answer** (in Hebrew, Pashto & Egyptian): **TL** in some lessons is from right to left (correct), but some are from left to right (incorrect); the same situation in **Reason**; i.e.  **Correct Answer** in ps_cul429, the direction of the first Answer (text) is from right to left (correct); but the rest of 4 Answers are from right to left.

**VID**: Once I click the link (open the lesson) and then the video is started to play voluntarily; I have no chance to read the instructions without clicking **Pause**. It’s very annoying. I couldn't read the **Instructions** quietly, after reading; the video clip is already in the middle of playing. **Suggest:** Let learners read **Instructions** first, and then click **Play **to watch the video clip.

**Note**: cm_mil200 (originally) is a video lesson, somehow, it is changed to an audio lesson in testing.

**Comment by ti-dm** [comment]
Resolved as of 3/17/16 for Correct Answer and VID
