### ISSUE TITLE
Scanning - feedback missing space

### ISSUE THREAD

**Issue by wendy-dliflc** [danb-dliflc/GLOSSActivities#41]
The second time I click "Submit" with incorrect answers, there is a space missing between the first and second sentence. 

Example:

http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/ps_cul332.xml&glossLoadActivityIndex=3&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/

![scanning fb](https://cloud.githubusercontent.com/assets/11760923/14323173/51161a3a-fbd4-11e5-9475-235afddfeb57.PNG)

**Comment by ti-dm** [comment]
Fixed and updated
