### ISSUE TITLE
Source Peripheral - Print

### ISSUE THREAD

**Issue by wendy-dliflc** [danb-dliflc/GLOSSActivities#43]
Julia looked into it and we will have the Print button and functionality for Glossary & Source. The button will likely be an image of a printer - we sent an e-mail to Mike about this.

Update: Got the print icon from Mike - it is called "icon_print_gray.png" and is in gloss2.lingnet.org/headstarthtml/templates/common/img

**Comment by ti-dm** [comment]
Updated

**Comment by ti-dm** [comment]
Updated as 4/26
