### ISSUE TITLE
Fill in the blanks 

### ISSUE THREAD

**Issue by dohee-koo** [danb-dliflc/GLOSSActivities#44]
1. In the Source box, the cursor changes into a horizontal arrow. It can give students an impression that the box is expandable while it isn’t now. 

2. In IE, the texts “Instructions” “More Info” and “Teacher’s Note” on the buttons are not centered. They are shifted to the left.

3. Italic font looks big in Glossary (check fr_soc310).

4. fr_sec301: In Glossary, the audio icons are on the right, so the layout is: 
French –-- English –-- audio icon

5. hbw_geo307 & hbw_cul326: In some feedback, Hebrew text is aligned to the left (it should be aligned to the right). I don’t see the same problem in the old interface.  I see this different alignment (from the original) here and there.

**Comment by wendy-dliflc** [comment]
1, 3, 4 moved to separate issues as appropriate since they relate to peripherals. 

2 is currently noted as a low priority item in the framework. 

5. This issue has been fixed.
