### ISSUE TITLE
Source Peripheral - Cursor

### ISSUE THREAD

**Issue by wendy-dliflc** [danb-dliflc/GLOSSActivities#45]
Moved from issue #44 (from Fill in the Blank testing by Dohee):

In the Source box, the cursor changes into a horizontal arrow. It can give students an impression that the box is expandable while it isn’t now.

**Comment by ti-dm** [comment]
It was "expandable-ready" but needed some more work in the frame.
Temporarily, I turned off the expandable function to make the cursor not to have the east-west arrow.

**Comment by ti-dm** [comment]
N/A anymore
