### ISSUE TITLE
Fill in the blanks - 2

### ISSUE THREAD

**Issue by dohee-koo** [danb-dliflc/GLOSSActivities#46]
Pashto LOs tested:

**ps_env325, ps_mil302**

In feedbacks, the alignment of the Pashto text is incorrect. It should be aligned to the right, not to the left. The text in the original feedback is correctly aligned.

**Ru_tec012, ru_soc320**

In Glossary, the audio icons are on the right, next to the English text. Please check with the PM (Julia) if this is the correct location. As far as I remember, audio icons should be next to the target language text, but please check with Julia. 

Another comments: When you upload LOs for testing, can you upload newer LOs? Older ones often do not have all the components (glossary audio files or resources), so they cannot be tested. Thanks!

**Comment by wendy-dliflc** [comment]
Alignment in feedback fixed. 

Glossary audio icons issue listed in Glossary issue (also discussed with Julia).
