### ISSUE TITLE
Source Peripheral testing

### ISSUE THREAD

**Issue by wendy-dliflc** [danb-dliflc/GLOSSActivities#50]
Moved from Issue #47, testing by Xiaomei for Listening True False and Fill in the Blank:

When the “source” is a video clip, and clicks on the “Source”, it still shows “audio play” button and also shows “Enable Alternate Audio”, but if I click the play button, it doesn’t work. If I click on the “Enable Alternate Audio”, it pops up a message “Unable to load audio”. See the capture below:
(Note: this is captured from Firefox, in IE11 and Chrome, the pop up message is a bit different.)

If I click audio play button in IE10, then the screen changes to gray and pause button in the middle of the page. See the capture.

Note: kp_cul257's source is a video clip, the below is the lesson link: http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/kp_cul257.xml&glossLoadActivityIndex=2&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/
Somehow I don't know how to attaché the images. So I attached my note with captures here.
Posted_6_21_2016.docx (Refer to Xiaomei's attachment in #47)

**Comment by ti-dm** [comment]
I'll take care of it.

**Comment by ti-dm** [comment]
Fixed it.
