### ISSUE TITLE
3 categorizing unmatched

### ISSUE THREAD

**Issue by dohee-koo** [danb-dliflc/GLOSSActivities#52]
The template is working well. The minor issues are the same as those of categorizing matched.

Tested LOs: ad_soc035, ad_soc040, pf_sci417, pf_soc440, ru_cul306, ru_soc035 (Korean and Chinese LOs were not uploaded, so were not tested.)

1. Texts on the buttons (Instruction, More Info, Teacher’s Note) are aligned to the left in IE. They may need to be centered. 

2. The category headings are not centered, unlike in the old interface, in ad_soc035, ru_cul306.

3. After drag & drop, the text is automatically aligned to the right (right-to-left languages) or left (left-to-right languages). Placing the text in the center will be better.

That's it for now. Thanks!

**Comment by wendy-dliflc** [comment]
1. Noted.
2. Changed so they are centered.
3. We decided to keep it aligned to left or right depending on the language direction. There have also been some recent design changes where having left or right aligned text makes more sense.
