### ISSUE TITLE
categorizing - unmatched

### ISSUE THREAD

**Issue by dohee-koo** [danb-dliflc/GLOSSActivities#53]
LO tested: ad_cul223, ad_geo402
Cm_cul025 (headings), cm_ecn305
Kp_cul409, kp_sec011
Pf_tec305, pf_mil307 (headings)
Ru_env217, ru_pol005 (headings)

Basically, the same comments with my comments for other matching templates.
The template works fine. Just need beautification.

1. Texts on the buttons (Instruction, More Info, Teacher’s Note) are aligned to the left in IE. They may need to be centered. 

2. The category headings are not centered, unlike in the old interface: cm_cul025, pf_mil307, ru_pol005. They are like that just for some LOs, not all.    

3. After drag & drop, the text is automatically aligned to the right (right-to-left languages) or left. Placing the text in the center will be better like in the old interface.

**Comment by wendy-dliflc** [comment]
1. Noted.
2. Changed so they are centered. 
3. We decided to keep it aligned to left or right depending on the language direction. There have also been some recent design changes where having left or right aligned text makes more sense.
