### ISSUE TITLE
Seg Multiple Answer - working fine

### ISSUE THREAD

**Issue by dohee-koo** [danb-dliflc/GLOSSActivities#54]
Tested: ars_cul459, ars_ecn438, kp_ecn271, kp_soc273, pf_geo416, pf_soc448
ru_sec218, cm_mil235, cm_sci237

The template is working fine.
Minor issues:
1. The texts on the buttons (Instruction, More Info, Teacher's Note) should be centered in IE. 
2. The scroll bar is not responsive in IE. Hard to control.

Other than that, everything works well.
Thank you.

**Comment by wendy-dliflc** [comment]
Ok, thanks!
