### ISSUE TITLE
Listening multiple choice

### ISSUE THREAD

**Issue by dohee-koo** [danb-dliflc/GLOSSActivities#55]
**Tested**: ars_ecn442, ars_pol426, cm_sci404, cm_soc426, kp_cul409, kp_sec233, pf_soc409, pf_tec409, ru_cul425, ru_soc2261. 

**1.** Texts on the buttons (Instruction, More Info, Teacher’s Note) are aligned to the left in IE. They should be centered. 

**2. ars_pol426, pf_tec409:** This is one-page activity. The right arrow next to “Item 1 of 1” is active (white), unlike the left arrow which is gray and inactive. The active arrow can give a wrong impression that there are more pages. When I clicked the right, white arrow, it turned gray. 

In Activity mode, the submit button appears when I select an answer. I can click the submit button and read the feedback. Clicking the white arrow turns it into gray, but doesn’t do anything else, so I think there is no reason to make it white?

In Quiz mode, the submit button appears not when I select an answer, but when I click the right active arrow after selecting an answer. I don’t know if this extra step of “clicking the arrow” is necessary, but please consult with Julia. This happens only in one-page activity. I tested cm_sci404 with 4-page activity. On the 4th page, the submit button appears when I select an answer. As soon as the activity turns to the last page (4), the right arrow automatically turns into gray. So there is lack of consistency.

**3.** In other templates, the print certificate button appeared in the pop-up feedback window (and in the activity window as well). In this template, the button doesn’t appear in the feedback window. 

**4.** I’m not sure it the Reset function is necessary. Without resetting, students can still choose a different answer. It may be more about preference? Please discuss with Julia.

Other functions work fine. Thank you!

**Comment by ti-dm** [comment]
#1 is IE problem
Fixed #2 and #3 
#4 stays there for consistence with other template

**Comment by ti-dm** [comment]
#4 stays there for consistency
