### ISSUE TITLE
RC-Multiple Choice

### ISSUE THREAD

**Issue by dohee-koo** [danb-dliflc/GLOSSActivities#57]
**Tested: ad_ecn151, ad_cul014, kp_soc214, ad_soc314, cm_cul064, cm_cul081
kp_sci030, pf_geo304, pf_mil326, ru_soc317, ru_tec007**

The issues are same with the LC multiple choice I posted previously. So I repeat them here.

**1.** Texts on the buttons (Instruction, More Info, Teacher’s Note) are aligned to the left in IE. They should be centered.

**2. Ad_cul014, kp_soc214:** This is one-page activity. The right arrow next to “Item 1 of 1” is active (white), unlike the left arrow which is gray and inactive. The active arrow can give a wrong impression that there are more pages. When I clicked the right, white arrow, it turned gray. 

In Activity mode, the submit button appears when I select an answer. I can click the submit button and read the feedback. Clicking the white arrow turns it into gray, but doesn’t do anything else, so I think there is no reason to make it white?

In Quiz mode, the submit button appears not when I select an answer, but when I click the right active arrow after selecting an answer. I don’t know if this extra step of “clicking the arrow” is necessary, but please consult with Julia. This happens only in one-page activity. On a multiple-page activity, as soon as the activity turns to the last page, the right arrow automatically turns into gray. So there is lack of consistency.

**3.** In other templates, the print certificate button appeared in the pop-up feedback window (and in the activity window as well). In this template, the button doesn’t appear in the feedback window.

**4.** I’m not sure it the Reset function is necessary. Without resetting, students can still choose a different answer. It may be more about preference? Please discuss with Julia.

**5. ad_ecn151**
Source: the enable alternate audio button is confusing. In the current interface, I don’t see an alternate audio. In the new interface, there is a button for the enable alternate audio. 

Other functions work fine. Thank you!

**Comment by ti-dm** [comment]
#1 is IE problem
Fixed #2 and #3 
#4 stays there for consistence with other template
Fixed #5

**Comment by ti-dm** [comment]
#4 stays there for consistency.
